/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './app/__root'
import { Route as IndexImport } from './app/index'
import { Route as WeeklyIndexImport } from './app/weekly/index'
import { Route as PodcastIndexImport } from './app/podcast/index'
import { Route as PodcastDateImport } from './app/podcast/$date'
import { Route as DateImport } from './app/$date'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WeeklyIndexRoute = WeeklyIndexImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => rootRoute,
} as any)

const PodcastIndexRoute = PodcastIndexImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRoute,
} as any)

const PodcastDateRoute = PodcastDateImport.update({
  id: '/podcast/$date',
  path: '/podcast/$date',
  getParentRoute: () => rootRoute,
} as any)

const DateRoute = DateImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$date': {
      id: '/$date'
      path: '/$date'
      fullPath: '/$date'
      preLoaderRoute: typeof DateImport
      parentRoute: typeof rootRoute
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastIndexImport
      parentRoute: typeof rootRoute
    }
    '/podcast/$date': {
      id: '/podcast/$date'
      path: '/podcast/$date'
      fullPath: '/podcast/$date'
      preLoaderRoute: typeof PodcastDateImport
      parentRoute: typeof rootRoute
    }
    '/weekly': {
      id: '/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof WeeklyIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  DateRoute,
  PodcastIndexRoute,
  PodcastDateRoute,
  WeeklyIndexRoute,
})

/* prettier-ignore-end */
